"""Final native entry: stable handle ABI backed by the standalone PortaPy VM."""
from __future__ import annotations

from .native_api import (
    portapy_abi_version,
    _portapy_error_clear_impl,
    _portapy_error_column_impl,
    _portapy_error_line_impl,
    _portapy_error_message_byte_impl,
    _portapy_error_message_size_impl,
    _portapy_error_status_impl,
    _portapy_error_type_byte_impl,
    _portapy_error_type_size_impl,
    _portapy_get_global_span_impl,
    _portapy_last_status_impl,
    _portapy_value_as_bool_impl,
    _portapy_value_as_f64_bits_impl,
    _portapy_value_as_i64_impl,
    _portapy_value_from_bool_impl,
    _portapy_value_from_data_begin_impl,
    _portapy_value_from_f64_bits_impl,
    _portapy_value_from_i64_impl,
    _portapy_value_from_none_impl,
    _portapy_value_get_byte_impl,
    _portapy_value_get_kind_impl,
    _portapy_value_get_size_impl,
    _portapy_value_release_impl,
    _portapy_value_retain_impl,
    _portapy_value_set_data_byte_impl,
    _portapy_value_validate_utf8_impl,
)
from .native_vm_bridge import (
    _portapy_eval_span_impl,
    _portapy_exec_span_impl,
    _portapy_runtime_create_impl,
    _portapy_runtime_destroy_impl,
)


__all__ = [
    "portapy_abi_version",
    "_portapy_runtime_create_impl",
    "_portapy_runtime_destroy_impl",
    "_portapy_exec_span_impl",
    "_portapy_eval_span_impl",
    "_portapy_get_global_span_impl",
    "_portapy_value_from_none_impl",
    "_portapy_value_from_bool_impl",
    "_portapy_value_from_i64_impl",
    "_portapy_value_from_f64_bits_impl",
    "_portapy_value_get_kind_impl",
    "_portapy_value_as_bool_impl",
    "_portapy_value_as_i64_impl",
    "_portapy_value_as_f64_bits_impl",
    "_portapy_value_retain_impl",
    "_portapy_value_release_impl",
    "_portapy_last_status_impl",
    "_portapy_value_from_data_begin_impl",
    "_portapy_value_set_data_byte_impl",
    "_portapy_value_validate_utf8_impl",
    "_portapy_value_get_size_impl",
    "_portapy_value_get_byte_impl",
    "_portapy_error_status_impl",
    "_portapy_error_line_impl",
    "_portapy_error_column_impl",
    "_portapy_error_type_size_impl",
    "_portapy_error_type_byte_impl",
    "_portapy_error_message_size_impl",
    "_portapy_error_message_byte_impl",
    "_portapy_error_clear_impl",
]
