#include "portapy.h"

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/* Python-authored implementation symbols generated by asmpython. */
extern int64_t portapy_internal_library_initialize(void);
extern int64_t portapy_internal_runtime_status(int64_t runtime);
extern int64_t portapy_internal_runtime_create(void);
extern int64_t portapy_internal_runtime_destroy(int64_t runtime);
extern int64_t portapy_internal_value_status(int64_t runtime, int64_t value);
extern int64_t portapy_internal_value_create_i64(int64_t runtime, int64_t value);
extern int64_t portapy_internal_value_retain(int64_t runtime, int64_t value);
extern int64_t portapy_internal_value_release(int64_t runtime, int64_t value);
extern int64_t portapy_internal_value_kind(int64_t runtime, int64_t value);
extern int64_t portapy_internal_value_i64(int64_t runtime, int64_t value);

struct portapy_runtime {
    int64_t handle;
    struct portapy_value *values;
};

struct portapy_value {
    int64_t handle;
    uint32_t references;
    struct portapy_runtime *runtime;
    struct portapy_value *previous;
    struct portapy_value *next;
};

static int portapy_initialized = 0;

static portapy_status portapy_status_from_i64(int64_t value) {
    if (value < PORTAPY_OK || value > PORTAPY_ABI_MISMATCH) {
        return PORTAPY_RUNTIME_ERROR;
    }
    return (portapy_status)value;
}

static portapy_status portapy_ensure_initialized(void) {
    int64_t status;
    if (portapy_initialized != 0) {
        return PORTAPY_OK;
    }
    status = portapy_internal_library_initialize();
    if (status != PORTAPY_OK) {
        return portapy_status_from_i64(status);
    }
    portapy_initialized = 1;
    return PORTAPY_OK;
}

static portapy_status portapy_validate_runtime(portapy_runtime *runtime) {
    if (runtime == NULL) {
        return PORTAPY_INVALID_ARGUMENT;
    }
    return portapy_status_from_i64(
        portapy_internal_runtime_status(runtime->handle)
    );
}

static portapy_status portapy_validate_value(
    portapy_runtime *runtime,
    portapy_value *value
) {
    portapy_status status = portapy_validate_runtime(runtime);
    if (status != PORTAPY_OK) {
        return status;
    }
    if (value == NULL || value->runtime != runtime) {
        return PORTAPY_INVALID_HANDLE;
    }
    return portapy_status_from_i64(
        portapy_internal_value_status(runtime->handle, value->handle)
    );
}

static void portapy_attach_value(
    portapy_runtime *runtime,
    portapy_value *value
) {
    value->previous = NULL;
    value->next = runtime->values;
    if (runtime->values != NULL) {
        runtime->values->previous = value;
    }
    runtime->values = value;
}

static void portapy_detach_value(portapy_value *value) {
    portapy_runtime *runtime = value->runtime;
    if (value->previous != NULL) {
        value->previous->next = value->next;
    } else if (runtime != NULL) {
        runtime->values = value->next;
    }
    if (value->next != NULL) {
        value->next->previous = value->previous;
    }
    value->runtime = NULL;
    value->previous = NULL;
    value->next = NULL;
}

PORTAPY_API uint32_t PORTAPY_CALL portapy_abi_version(void) {
    return PORTAPY_ABI_VERSION;
}

PORTAPY_API const char *PORTAPY_CALL portapy_version_string(void) {
    return "3.14.0-dev";
}

PORTAPY_API portapy_status PORTAPY_CALL portapy_runtime_create(
    const portapy_config *config,
    portapy_runtime **out_runtime
) {
    portapy_runtime *runtime;
    portapy_status status;
    int64_t handle;
    const size_t minimum_config_size =
        offsetof(portapy_config, flags) + sizeof(config->flags);

    if (out_runtime == NULL) {
        return PORTAPY_INVALID_ARGUMENT;
    }
    *out_runtime = NULL;

    if (config != NULL) {
        if (config->struct_size < minimum_config_size) {
            return PORTAPY_INVALID_ARGUMENT;
        }
        if (config->abi_version != PORTAPY_ABI_VERSION) {
            return PORTAPY_ABI_MISMATCH;
        }
    }

    status = portapy_ensure_initialized();
    if (status != PORTAPY_OK) {
        return status;
    }

    handle = portapy_internal_runtime_create();
    if (handle == 0) {
        return PORTAPY_RUNTIME_ERROR;
    }

    runtime = (portapy_runtime *)calloc(1, sizeof(*runtime));
    if (runtime == NULL) {
        (void)portapy_internal_runtime_destroy(handle);
        return PORTAPY_RUNTIME_ERROR;
    }
    runtime->handle = handle;
    runtime->values = NULL;
    *out_runtime = runtime;
    return PORTAPY_OK;
}

PORTAPY_API portapy_status PORTAPY_CALL portapy_runtime_destroy(
    portapy_runtime *runtime
) {
    portapy_status status;
    portapy_value *value;
    portapy_value *next;

    status = portapy_validate_runtime(runtime);
    if (status != PORTAPY_OK) {
        return status;
    }

    status = portapy_status_from_i64(
        portapy_internal_runtime_destroy(runtime->handle)
    );
    if (status != PORTAPY_OK) {
        return status;
    }

    value = runtime->values;
    while (value != NULL) {
        next = value->next;
        value->runtime = NULL;
        free(value);
        value = next;
    }
    runtime->values = NULL;
    runtime->handle = 0;
    free(runtime);
    return PORTAPY_OK;
}

PORTAPY_API portapy_status PORTAPY_CALL portapy_value_from_i64(
    portapy_runtime *runtime,
    int64_t payload,
    portapy_value **out_value
) {
    portapy_status status = portapy_validate_runtime(runtime);
    portapy_value *value;
    int64_t handle;

    if (status != PORTAPY_OK) {
        return status;
    }
    if (out_value == NULL) {
        return PORTAPY_INVALID_ARGUMENT;
    }
    *out_value = NULL;

    handle = portapy_internal_value_create_i64(runtime->handle, payload);
    if (handle == 0) {
        return PORTAPY_RUNTIME_ERROR;
    }

    value = (portapy_value *)calloc(1, sizeof(*value));
    if (value == NULL) {
        (void)portapy_internal_value_release(runtime->handle, handle);
        return PORTAPY_RUNTIME_ERROR;
    }
    value->handle = handle;
    value->references = 1;
    value->runtime = runtime;
    portapy_attach_value(runtime, value);
    *out_value = value;
    return PORTAPY_OK;
}

PORTAPY_API portapy_status PORTAPY_CALL portapy_value_retain(
    portapy_runtime *runtime,
    portapy_value *value
) {
    portapy_status status = portapy_validate_value(runtime, value);
    if (status != PORTAPY_OK) {
        return status;
    }
    status = portapy_status_from_i64(
        portapy_internal_value_retain(runtime->handle, value->handle)
    );
    if (status == PORTAPY_OK) {
        value->references += 1;
    }
    return status;
}

PORTAPY_API portapy_status PORTAPY_CALL portapy_value_release(
    portapy_runtime *runtime,
    portapy_value *value
) {
    portapy_status status = portapy_validate_value(runtime, value);
    if (status != PORTAPY_OK) {
        return status;
    }
    status = portapy_status_from_i64(
        portapy_internal_value_release(runtime->handle, value->handle)
    );
    if (status != PORTAPY_OK) {
        return status;
    }

    if (value->references > 1) {
        value->references -= 1;
        return PORTAPY_OK;
    }

    value->references = 0;
    portapy_detach_value(value);
    value->handle = 0;
    free(value);
    return PORTAPY_OK;
}

PORTAPY_API portapy_status PORTAPY_CALL portapy_value_get_kind(
    portapy_runtime *runtime,
    portapy_value *value,
    portapy_value_kind *out_kind
) {
    portapy_status status = portapy_validate_value(runtime, value);
    int64_t kind;
    if (status != PORTAPY_OK) {
        return status;
    }
    if (out_kind == NULL) {
        return PORTAPY_INVALID_ARGUMENT;
    }
    kind = portapy_internal_value_kind(runtime->handle, value->handle);
    if (kind < PORTAPY_VALUE_NONE || kind > PORTAPY_VALUE_OBJECT) {
        return PORTAPY_RUNTIME_ERROR;
    }
    *out_kind = (portapy_value_kind)kind;
    return PORTAPY_OK;
}

PORTAPY_API portapy_status PORTAPY_CALL portapy_value_as_i64(
    portapy_runtime *runtime,
    portapy_value *value,
    int64_t *out_value
) {
    portapy_status status = portapy_validate_value(runtime, value);
    int64_t kind;
    if (status != PORTAPY_OK) {
        return status;
    }
    if (out_value == NULL) {
        return PORTAPY_INVALID_ARGUMENT;
    }
    kind = portapy_internal_value_kind(runtime->handle, value->handle);
    if (kind != PORTAPY_VALUE_INT) {
        return PORTAPY_TYPE_ERROR;
    }
    *out_value = portapy_internal_value_i64(runtime->handle, value->handle);
    return PORTAPY_OK;
}
